"""initial_schema

Revision ID: 3b14b6447ad0
Revises: 
Create Date: 2025-12-03 09:19:04.176249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b14b6447ad0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('epic', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('NEW_PROJECT', 'EXISTING_PROJECT_BUG', 'EXISTING_PROJECT_FEATURE', name='projecttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ANALYZING', 'FEATURES_PENDING_REVIEW', 'FEATURES_REJECTED', 'APPROVED', 'REPO_CREATING', 'REPO_CREATED', 'PBIS_CREATING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='projectstatus'), nullable=False),
    sa.Column('github_repo_url', sa.String(length=500), nullable=True),
    sa.Column('github_repo_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PR_PENDING', 'COMPLETED', name='featurestatus'), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    op.create_table('pbis',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('BACKEND', 'FRONTEND', name='pbitype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PR_CREATED', 'PR_CHANGES_REQUESTED', 'PR_APPROVED', 'COMPLETED', 'BLOCKED', 'FAILED', name='pbistatus'), nullable=False),
    sa.Column('assigned_agent', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_status', sa.Enum('OPEN', 'CHANGES_REQUESTED', 'APPROVED', 'MERGED', 'CLOSED', name='prstatus'), nullable=True),
    sa.Column('blocked_by_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by_id'], ['pbis.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pbis_feature_id'), 'pbis', ['feature_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pbi_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.Enum('THOUGHT', 'ACTION', 'CODE', 'ERROR', 'COMMUNICATION', name='agentmessagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pbi_id'], ['pbis.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_pbi_id'), 'agent_logs', ['pbi_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_project_id'), 'agent_logs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_project_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_pbi_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_pbis_feature_id'), table_name='pbis')
    op.drop_table('pbis')
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    op.drop_table('features')
    op.drop_table('projects')
    # ### end Alembic commands ###
